### ISSUE TITLE
create a bower component

### ISSUE THREAD

**Issue by meodai** [ultrapasty/jquery-disablescroll#3]
hello, could you do a bower component? Would be super useful. http://bower.io/docs/creating-packages/

**Comment by ultrapasty** [comment]
I agree, but I don't yet understand semver or git tagging and right now don't have the time to learn it, sorry. Will do when I get a chance to pick it up.

**Comment by ultrapasty** [comment]
I know it's not the same but for now you could just grab the file directly through bower:

    "dependencies": {
        "jquery-disablescroll": "https://raw.githubusercontent.com/ultrapasty/jquery-disablescroll/master/jquery.disablescroll.min.js"
    }

**Comment by corysimmons** [comment]
It's super easy to create a Bower package and you can create tags right in the GitHub UI. http://bower.io/docs/creating-packages
