### ISSUE TITLE
is there a way to prevent event propagation

### ISSUE THREAD

**Issue by renatodeleao** [ultrapasty/jquery-disablescroll#7]
I'm currently using your plugin to prevent this bootstrap iOS 8 > bug https://github.com/twbs/bootstrap/pull/16380 .

What i'm doing is preventing body scroll when modal open:

```
var $nonScrollable = $("body");
     
              $('.modal').on('show.bs.modal', function(e){
                alert('scroll disabled');
                $nonScrollable.disablescroll();
               
              });

              $('.modal').on('hidden.bs.modal', function(e){
                $nonScrollable.disablescroll("undo");
              });
```

what happen is that i have scrollable modals, and scrollable divs inside modals that are now blocked.
Any thoughts on how to workaround this?

PS: moving modals outside body could be your first though, but due the size of the team and project, I would rather not doing that.

Thanks in advance!

**Comment by ultrapasty** [comment]
Interesting problem. Are you able to create a jsfiddle demonstrating the problem that I can have a play around in?

**Comment by renatodeleao** [comment]
@ultrapasty off course!

here, take this [pen](http://codepen.io/ohsimtabem/pen/oXXYGz)!

Thanks for the quick reply!

**Comment by ultrapasty** [comment]
Sorry for the massive delay.

Based on your pen, you actually don't seem to need my plugin at all! (See pen)[http://codepen.io/anon/pen/oXYJKW]. I can scroll the long modal and its inner scroll panel, but not the body. Is that the expected behaviour?

You've probably found a way around this by now anyway.

**Comment by MKahmen** [comment]
Hi @ultrapasty 

Have a pretty similar problem... I disable scrolling for the whole document:
`$(document).disablescroll({ handleWheel: false });`
works fine.

After I close my modal it calls `$(document).disablescroll("undo");`

If I reopen my modal again, it jumps back into my callback and calls `$(document).disablescroll({ handleWheel: false });` again. But it doesnt work...

Any ideas?

Greets

**Comment by ultrapasty** [comment]
Hi @MKahmen - this is a different issue. Please open a new one with a link to an example jsfiddle or similar demonstrating the problem.
