### ISSUE TITLE
disablescroll() -> undo -> disablescroll() does not work

### ISSUE THREAD

**Issue by MKahmen** [ultrapasty/jquery-disablescroll#8]
disablescroll-Method does not work again after "undo" is called.

Here's my fiddle:

http://jsfiddle.net/akhaak0g/3/

Please see JS-part:
`$(window).disablescroll({ handleWheel: false });
$(window).disablescroll("undo");
$(window).disablescroll({ handleWheel: false });`

**Comment by ultrapasty** [comment]
Hi @MKahmen, I've had a look into it. 

Just make sure you only pass the options on first use. So this should work as expected:

    $(window).disablescroll({ handleWheel: false });
    $(window).disablescroll("undo");
    $(window).disablescroll();

Perhaps I will alter this in the future, so that different options can be passed in at any time. Fairly sure that wouldn't be standard jQuery plugin behaviour though.
