### ISSUE TITLE
Disables spacebar use on input fields

### ISSUE THREAD

**Issue by alexmccabe** [ultrapasty/jquery-disablescroll#9]
Disables the use of spacebar on input fields, which as you can imagine, can be a bit irritating. Haha. I need to disable the scroll on a window, but I also need to have an input field displayed.

**Comment by alexmccabe** [comment]
Sorry, refactored code. Solved my problem

**Comment by ultrapasty** [comment]
Glad you solved it. Would you mind sharing your solution?

**Comment by alexmccabe** [comment]
I had a function that would show an overlay, and in doing so would disable scrolling. As in this case I was only using it on a mobile view, the spacebar would never be shown unless the input was focussed I used your handle keys option.

    EOApp.showOverlay = function (handleKeys) {
        EOApp.body.stop().addClass('overlay-open');
        EOApp.$window.disablescroll({
            handleKeys: handleKeys ? true : false
        });
    };
